#!/usr/bin/env python3
"""
Mirrors XTest fake-input events (as generated by RemoteMouse via python-xlib)
into a real uinput virtual mouse device, so KWin's Wayland compositor
actually moves the visible cursor. XTest events alone update XWayland's
shadow pointer position but are not forwarded into the real Wayland input
pipeline by modern KWin (security restriction), so the fix is to replay them
through a kernel-level virtual device that looks like real hardware.

Only listens to XI2 events from device id 4 ("Virtual core XTEST pointer"),
never from any other device, so this cannot create a feedback loop with the
motion it emits itself (that motion arrives back in XWayland under an
unrelated "xwayland-pointer" device id, which is not selected here).
"""
import os
import sys
import time

os.environ.setdefault("DISPLAY", ":0")

from Xlib import display
from evdev import UInput, AbsInfo, ecodes as e

XTEST_DEVICE_ID = 4
MOTION, BUTTON_PRESS, BUTTON_RELEASE = 6, 4, 5

BUTTON_MAP = {
    1: e.BTN_LEFT,
    2: e.BTN_MIDDLE,
    3: e.BTN_RIGHT,
}
WHEEL_UP, WHEEL_DOWN = 4, 5


def build_caps(screen_w, screen_h):
    # Absolute positioning (like a graphics tablet) instead of relative deltas:
    # XTest events are already-accelerated absolute coordinates, so replaying
    # them as relative motion would run them through libinput's pointer
    # acceleration a second time, producing sluggish/non-linear feeling
    # movement. Absolute devices bypass acceleration entirely in libinput.
    return {
        e.EV_ABS: [
            (e.ABS_X, AbsInfo(value=0, min=0, max=screen_w, fuzz=0, flat=0, resolution=0)),
            (e.ABS_Y, AbsInfo(value=0, min=0, max=screen_h, fuzz=0, flat=0, resolution=0)),
        ],
        e.EV_KEY: [e.BTN_LEFT, e.BTN_RIGHT, e.BTN_MIDDLE],
        e.EV_REL: [e.REL_WHEEL],
    }


def find_xtest_device_id(d):
    from Xlib.ext import xinput
    for dev in xinput.query_device(d, xinput.AllDevices).devices:
        if dev.name == "Virtual core XTEST pointer":
            return dev.deviceid
    return XTEST_DEVICE_ID


def main():
    d = display.Display()
    screen = d.screen()
    root = screen.root
    from Xlib.ext import xinput

    device_id = find_xtest_device_id(d)
    print(f"[bridge] mirroring XTEST device id={device_id}", flush=True)

    root.xinput_select_events([
        (device_id, [xinput.MotionMask | xinput.ButtonPressMask | xinput.ButtonReleaseMask])
    ])
    d.sync()

    while d.pending_events():
        d.next_event()

    caps = build_caps(screen.width_in_pixels, screen.height_in_pixels)
    ui = UInput(caps, name="remotemouse-xtest-bridge")
    print("[bridge] virtual input device created, ready", flush=True)

    try:
        while True:
            ev = d.next_event()
            if ev.type != 35:
                continue
            data = ev.data
            if ev.evtype == MOTION:
                ui.write(e.EV_ABS, e.ABS_X, int(round(data.root_x)))
                ui.write(e.EV_ABS, e.ABS_Y, int(round(data.root_y)))
                ui.syn()
            elif ev.evtype == BUTTON_PRESS:
                button = data.detail
                if button in (WHEEL_UP, WHEEL_DOWN):
                    ui.write(e.EV_REL, e.REL_WHEEL, 1 if button == WHEEL_UP else -1)
                    ui.syn()
                elif button in BUTTON_MAP:
                    ui.write(e.EV_KEY, BUTTON_MAP[button], 1)
                    ui.syn()
            elif ev.evtype == BUTTON_RELEASE:
                button = data.detail
                if button in BUTTON_MAP:
                    ui.write(e.EV_KEY, BUTTON_MAP[button], 0)
                    ui.syn()
    finally:
        ui.close()


if __name__ == "__main__":
    while True:
        try:
            main()
        except Exception as exc:
            print(f"[bridge] crashed: {exc!r}, restarting in 2s", file=sys.stderr, flush=True)
            time.sleep(2)
