#!/usr/bin/env python3
"""
Mirrors XTest fake-input events (as generated by RemoteMouse via python-xlib)
into real uinput virtual mouse + keyboard devices, so KWin's Wayland
compositor actually moves the visible cursor and types the pressed keys.
XTest events alone update XWayland's shadow pointer/key state but are not
forwarded into the real Wayland input pipeline by modern KWin (security
restriction), so the fix is to replay them through kernel-level virtual
devices that look like real hardware.

Only listens to XI2 events from the two dedicated XTEST devices ("Virtual
core XTEST pointer" / "Virtual core XTEST keyboard"), never from any other
device, so this cannot create a feedback loop with the input it emits
itself (that motion/state arrives back in XWayland under unrelated
"xwayland-pointer"/"xwayland-keyboard" device ids, which are not selected
here).
"""
import os
import sys
import time

os.environ.setdefault("DISPLAY", ":0")

from Xlib import display
from evdev import UInput, AbsInfo, ecodes as e

MOTION = 6
KEY_PRESS, KEY_RELEASE = 2, 3
BUTTON_PRESS, BUTTON_RELEASE = 4, 5

BUTTON_MAP = {
    1: e.BTN_LEFT,
    2: e.BTN_MIDDLE,
    3: e.BTN_RIGHT,
}
WHEEL_UP, WHEEL_DOWN = 4, 5

# X11 keycode = Linux/evdev keycode + 8. This offset is a fixed convention
# of every Linux X server using the evdev/libinput input driver (verified
# empirically: 'a' arrives as X11 keycode 38, and evdev KEY_A == 30).
KEYCODE_OFFSET = 8

# Every standard evdev keyboard keycode (1..247, covering letters, function
# keys, and media keys), so any key RemoteMouse's virtual keyboard sends is
# already declared as a capability up front.
ALL_KEY_CODES = list(range(1, 248))


def build_caps(screen_w, screen_h):
    # Absolute positioning (like a graphics tablet) instead of relative deltas:
    # XTest events are already-accelerated absolute coordinates, so replaying
    # them as relative motion would run them through libinput's pointer
    # acceleration a second time, producing sluggish/non-linear feeling
    # movement. Absolute devices bypass acceleration entirely in libinput.
    return {
        e.EV_ABS: [
            (e.ABS_X, AbsInfo(value=0, min=0, max=screen_w, fuzz=0, flat=0, resolution=0)),
            (e.ABS_Y, AbsInfo(value=0, min=0, max=screen_h, fuzz=0, flat=0, resolution=0)),
        ],
        e.EV_KEY: [e.BTN_LEFT, e.BTN_RIGHT, e.BTN_MIDDLE] + ALL_KEY_CODES,
        e.EV_REL: [e.REL_WHEEL],
    }


def find_xtest_device_ids(d):
    from Xlib.ext import xinput
    pointer_id = keyboard_id = None
    for dev in xinput.query_device(d, xinput.AllDevices).devices:
        if dev.name == "Virtual core XTEST pointer":
            pointer_id = dev.deviceid
        elif dev.name == "Virtual core XTEST keyboard":
            keyboard_id = dev.deviceid
    if pointer_id is None or keyboard_id is None:
        raise RuntimeError("could not find Virtual core XTEST pointer/keyboard devices")
    return pointer_id, keyboard_id


def main():
    d = display.Display()
    screen = d.screen()
    root = screen.root
    from Xlib.ext import xinput

    pointer_id, keyboard_id = find_xtest_device_ids(d)
    print(f"[bridge] mirroring XTEST pointer id={pointer_id}, keyboard id={keyboard_id}", flush=True)

    root.xinput_select_events([
        (pointer_id, [xinput.MotionMask | xinput.ButtonPressMask | xinput.ButtonReleaseMask]),
        (keyboard_id, [xinput.KeyPressMask | xinput.KeyReleaseMask]),
    ])
    d.sync()

    while d.pending_events():
        d.next_event()

    caps = build_caps(screen.width_in_pixels, screen.height_in_pixels)
    ui = UInput(caps, name="remotemouse-xtest-bridge")
    print("[bridge] virtual input device created, ready", flush=True)

    try:
        while True:
            ev = d.next_event()
            if ev.type != 35:
                continue
            data = ev.data
            if ev.evtype == MOTION:
                ui.write(e.EV_ABS, e.ABS_X, int(round(data.root_x)))
                ui.write(e.EV_ABS, e.ABS_Y, int(round(data.root_y)))
                ui.syn()
            elif ev.evtype == BUTTON_PRESS:
                button = data.detail
                if button in (WHEEL_UP, WHEEL_DOWN):
                    ui.write(e.EV_REL, e.REL_WHEEL, 1 if button == WHEEL_UP else -1)
                    ui.syn()
                elif button in BUTTON_MAP:
                    ui.write(e.EV_KEY, BUTTON_MAP[button], 1)
                    ui.syn()
            elif ev.evtype == BUTTON_RELEASE:
                button = data.detail
                if button in BUTTON_MAP:
                    ui.write(e.EV_KEY, BUTTON_MAP[button], 0)
                    ui.syn()
            elif ev.evtype == KEY_PRESS:
                code = data.detail - KEYCODE_OFFSET
                if code in ALL_KEY_CODES:
                    ui.write(e.EV_KEY, code, 1)
                    ui.syn()
            elif ev.evtype == KEY_RELEASE:
                code = data.detail - KEYCODE_OFFSET
                if code in ALL_KEY_CODES:
                    ui.write(e.EV_KEY, code, 0)
                    ui.syn()
    finally:
        ui.close()


if __name__ == "__main__":
    while True:
        try:
            main()
        except Exception as exc:
            print(f"[bridge] crashed: {exc!r}, restarting in 2s", file=sys.stderr, flush=True)
            time.sleep(2)
